### ISSUE TITLE
Make the sleep between health check configurable

### ISSUE THREAD

**Issue by darkrift** [dzbarsky/rules_itest#14]
The health check sleep time is hardcoded at 200ms, however it happens sometimes that the task or the service to be spun up can take a little bit of time which makes it useless to poke too often. Poking it too often also clutters the logs with too many health check error messages.

Of course, setting the sleep time too high can slow down the tests, but just raising this to 500ms would be good enough sometimes.

**Comment by DavidZbarsky-at** [comment]
I'll make it configurable.
