### ISSUE TITLE
Request for license clarification

### ISSUE THREAD

**Issue by engnatha** [dzbarsky/rules_itest#32]
Hey rules_itest maintainers!

We're evaluating pulling this in for assisting our more complicated unit tests. There's no official license listed in the repo root, so we are hoping to get clarification on allowed usage here. Would that be possible to get updated?

**Comment by dzbarsky** [comment]
Hi, I've added an MIT license. I'm guessing that works for you, but please let me know if it doesn't and we can figure something out.

**Comment by engnatha** [comment]
Yes, that's perfect. Thanks for handling that so quickly! Looking forward to trying it out.
